import { Icon } from './Icon';
import { Loadout } from './Loadout';

export function Help() {
  return <section className="content-page help-page"><div className="page-title"><h1>Make every life count.</h1><p>Five minutes. Fifteen eliminations. A new rivalry every round.</p></div>
    <div className="help-columns"><section><h2><Icon name="desktop"/> Desktop</h2><dl className="controls-list"><div><dt>Move</dt><dd><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd></dd></div><div><dt>Look</dt><dd>Mouse</dd></div><div><dt>Fire / use healing</dt><dd>Left click</dd></div><div><dt>Aim</dt><dd>Hold right click</dd></div><div><dt>Sprint / jump</dt><dd><kbd>Shift</kbd> / <kbd>Space</kbd></dd></div><div><dt>Reload</dt><dd><kbd>R</kbd></dd></div><div><dt>Switch slot</dt><dd><kbd>1</kbd><kbd>2</kbd><kbd>3</kbd></dd></div><div><dt>Release mouse</dt><dd><kbd>Esc</kbd></dd></div></dl></section>
    <section><h2><Icon name="phone"/> Phone</h2><dl className="controls-list"><div><dt>Move</dt><dd>Left thumbstick</dd></div><div><dt>Look</dt><dd>Drag the right side</dd></div><div><dt>Simple firing</dt><dd>Rest the reticle on a rival to auto-fire</dd></div><div><dt>Advanced firing</dt><dd>Hold and drag Fire to aim and shoot</dd></div><div><dt>Healing</dt><dd>Select slot 3, then tap Heal</dd></div><div><dt>Gyroscope</dt><dd>Enable in Settings to aim by tilting</dd></div><div><dt>Aim / jump / reload</dt><dd>Right-side buttons</dd></div><div><dt>Switch slot</dt><dd>Tap your loadout</dd></div><div><dt>Best view</dt><dd>Turn your phone sideways</dd></div></dl><p className="muted">Simple firing is on by default. Choose Advanced in Settings for manual control. Landscape gives you the most room. Set graphics to Low if your phone needs a smoother frame rate.</p></section></div>
    <section className="rules-section"><h2>Equal loadouts. Better rivalries.</h2><Loadout compact/><div className="rule-copy"><p><strong>Three-second respawns.</strong> Return with 100 health, 50 shield, full magazines, and two healing charges. Two seconds of spawn protection ends when you fire.</p><p><strong>Healing takes commitment.</strong> Select slot 3 and use it to restore 50 health over three seconds. Taking damage or firing a weapon interrupts it. Healing does not refill shield.</p><p><strong>Your crew decides the competition.</strong> Casual and practice matches never change ratings. Ranked crew matches need at least two people and one minute of play. Finish five eligible matches to place; only the first five results against the same opponent each day count.</p></div></section>
  </section>;
}
